apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplewebhook
  labels:
    app: simplewebhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simplewebhook
  template:
    metadata:
      labels:
        app: simplewebhook
    spec:
      containers:
      - name: simplewebhook
        image: ghcr.io/kengou/simplewebhook:main
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        securityContext:
          runAsUser: 65532
          runAsGroup: 65532
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
